#include "main.h"
#include "basestation.h"

struct infrared { // struct to store infrared reports generated by threads
    int reading;
    int node;
    char timestamp[26];
};

// represents the base station in WSN
// params
// rank: rank of base station
// size: total number of nodes in 2D sensor grid
// report: struct when receive report from sensor nodes
// struct_type: struct type of report
void base_station(int rank, int size, struct report_struct report, MPI_Datatype struct_type) {
    struct infrared inf_reports[100]; // store reports generated by infrared
    sleep(1); // TODO: change to thread to generate reading

    int i, msg = 0, flag, sensor_reading;
    while (msg < size-1) { // listen to sensor nodes to check for alert
        MPI_Status stat;
        for (i = 0; i < size; i++) {
            MPI_Iprobe(MPI_ANY_SOURCE, BASE_TAG, MPI_COMM_WORLD, &flag, &stat);
            if (flag) { // there exists a message
                MPI_Recv(&report, 1, struct_type, stat.MPI_SOURCE, BASE_TAG, MPI_COMM_WORLD, &stat);
                printf("base-- from %d read %d msg %d time %s", stat.MPI_SOURCE, report.reading, report.num_msg, report.timestamp);
                // TODO: after receive must compare with readings in reports
                break;
            }
        }
        msg++;
    }
}
