#include "main.h"
#include "basestation.h"

struct infrared { // struct to store infrared reports generated by threads
    int reading;
    int node;
    char timestamp[26];
};

void base_station(int rank, int size, struct report_struct report, MPI_Datatype struct_type) {
    struct infrared inf_reports[100]; // store reports generated by infrared
    sleep(1); // TODO: change to thread to generate reading
    int i;
    int msg = 0, flag, sensor_reading;
    while (msg < size-1) {
        MPI_Status stat;
        for (i = 0; i < size; i++) {
            MPI_Iprobe(MPI_ANY_SOURCE, BASE_TAG, MPI_COMM_WORLD, &flag, &stat);
            if (flag) { // there exists a message
                MPI_Recv(&report, 1, struct_type, stat.MPI_SOURCE, BASE_TAG, MPI_COMM_WORLD, &stat);
                printf("base-- from %d read %d msg %d time %s", stat.MPI_SOURCE, report.reading, report.num_msg, report.timestamp);
                // TODO: after receive must compared with readings in reports
                break;
            }
        }
        msg++;
    }
}
